import 'package:flutter/material.dart';
import 'package:shared_preferences/shared_preferences.dart';

class LocalizationService extends ChangeNotifier {
  static final LocalizationService _instance = LocalizationService._internal();

  static LocalizationService get instance => _instance;

  LocalizationService._internal();

  // 'si' for Sinhala, 'en' for English
  String _currentLocale = 'si';
  bool _hasSetLanguage = false;

  String get currentLocale => _currentLocale;
  bool get hasSetLanguage => _hasSetLanguage;

  static const String _localeKey = 'sipsara_language_code';
  static const String _hasSetLanguageKey = 'sipsara_has_set_language';

  Future<void> init() async {
    final prefs = await SharedPreferences.getInstance();
    _currentLocale = prefs.getString(_localeKey) ?? 'si';
    _hasSetLanguage = prefs.getBool(_hasSetLanguageKey) ?? false;
  }

  Future<void> setLocale(String localeCode) async {
    if (_currentLocale == localeCode) return;
    _currentLocale = localeCode;
    
    // Once they explicitly change the language, mark it as set
    _hasSetLanguage = true;
    
    final prefs = await SharedPreferences.getInstance();
    await prefs.setString(_localeKey, _currentLocale);
    await prefs.setBool(_hasSetLanguageKey, true);
    
    notifyListeners();
  }
  
  Future<void> markLanguageAsSet() async {
    if (_hasSetLanguage) return;
    _hasSetLanguage = true;
    final prefs = await SharedPreferences.getInstance();
    await prefs.setBool(_hasSetLanguageKey, true);
    notifyListeners();
  }

  String t(String key) {
    return _translations[_currentLocale]?[key] ?? _translations['en']?[key] ?? key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'si': {
      'welcome_title': 'ආයුබෝවන්!',
      'welcome_subtitle': 'ඔබගේ සිංහල ඉගෙනුම්\nවික්‍රමය මෙතැනින් අරඹන්න!',
      'welcome_btn_signup': 'ආරම්භ කරන්න',
      'welcome_btn_signin': 'මට දැනටමත් ගිණුමක් ඇත',
      'btn_signin': 'ඇතුළු වන්න',
      'signing_in': 'ඇතුළු වෙමින්...',
      'btn_signup': 'ලියාපදිංචි වන්න',
      'email': 'ඊමේල්',
      'email_hint': 'විද්‍යුත් තැපැල් ලිපිනය',
      'password': 'මුරපදය',
      'password_hint': 'ඔබගේ මුරපදය',
      'password_hint_create': 'මුරපදයක් සාදන්න',
      'forgot_password': 'මුරපදය අමතකද?',
      'forgot_password_desc': 'කණගාටු නොවන්න! ඔබගේ විද්‍යුත් තැපැල් ලිපිනය ඇතුලත් කරන්න. මුරපදය නැවත සැකසීමට අපි පින් අංකයක් එවන්නෙමු.',
      'sending_code': 'කේතය යවමින් පවතී...',
      'send_code': 'කේතය යවන්න',
      'check_email': 'ඔබගේ විද්‍යුත් තැපෑල පරීක්ෂා කරන්න',
      'otp_sent_to': 'අපි අංක 6 කින් යුත් කේතයක් යවා ඇත\n',
      'otp_enter_below': '.\nඔබගේ ගිණුම තහවුරු කිරීමට එය පහතින් ඇතුලත් කරන්න.',
      'resend_code_in': 'තත්පර {time} කින් නැවත එවන්න',
      'resend_otp_now': 'දැන් නැවත කේතය යවන්න',
      'verify_code': 'කේතය තහවුරු කරන්න',
      'dont_have_account': 'ඔබට ගිණුමක් නොමැතිද? ',
      'already_have_account': 'ඔබට දැනටමත් ගිණුමක් තිබේද? ',
      'signin_title': 'නැවතත් සාදරයෙන් පිළිගනිමු!',
      'signin_subtitle': 'ඔබගේ ඉගෙනුම් වික්‍රමය ආරම්භ කිරීමට ඇතුළු වන්න',
      'signup_title': 'ඔබගේ ගිණුම සාදන්න',
      'signup_subtitle': 'අදම ඔබගේ ඉගෙනුම් වික්‍රමයට එක්වන්න',
      'parent_name': 'දෙමාපියන්ගේ නම',
      'parent_name_hint': 'ඔබගේ නම',
      'role_parent': 'දෙමාපිය',
      'role_therapist': 'චිකිත්සක',
      'specialization_hint': 'විශේෂඥතාව (කථන චිකිත්සක)',
      'clinic_hint': 'සායනයේ නම (විකල්ප)',
      'or': 'හෝ',
      'mobile_number': 'දුරකථන අංකය',
      'mobile_number_hint': 'ඔබගේ දුරකථන අංකය',
      'confirm_password': 'මුරපදය තහවුරු කරන්න',
      'confirm_password_hint': 'මුරපදය නැවත ඇතුලත් කරන්න',
      'agree_terms': 'සිප්සර භාවිතා කිරීමේ නියමයන්ට හා රහස්‍යතා ප්‍රතිපත්තියට එකඟ වෙමි.',
      'benefit_private': 'පෞද්ගලික',
      'start_assessment': 'ඇගයීම ආරම්භ කරන්න',
      'maybe_later': 'පසුව බලමු',
      'assessment_later_desc': 'ඔබට මෙය සිසුවාගේ ගිණුමෙන් ඕනෑම වේලාවක ආරම්භ කළ හැක.',
      'start_from_profile': 'ඔබට මෙය සිසුවාගේ ගිණුමෙන් පසුව ආරම්භ කළ හැක.',
      'language': 'භාෂාව',
      'select_language': 'භාෂාව තෝරන්න',
      'settings': 'විකල්ප',
      'field_required': 'මෙම තොරතුර අනිවාර්යයි',
      'invalid_email': 'වලංගු ඊමේල් ලිපිනයක් ඇතුලත් කරන්න',
      'invalid_phone': 'වලංගු දුරකථන අංකයක් ඇතුලත් කරන්න',
      'password_short': 'මුරපදය අවම වශයෙන් අකුරු 6 කින් යුක්ත විය යුතුය',
      'passwords_dont_match': 'මුරපද සමාන නොවේ',
      'must_agree_terms': 'ඔබ නියමයන්ට හා රහස්‍යතා ප්‍රතිපත්තියට එකඟ විය යුතුය',
      'or_continue_with': 'නැතහොත් මේ සමඟ දිගටම යන්න',
      'error_occurred': 'දෝෂයක් ඇතිවිය. කරුණාකර නැවත උත්සාහ කරන්න.',
      'change': 'වෙනස් කරන්න',
      'parent_account': 'දෙමාපිය ගිණුම',
      'account_security': 'ගිණුම සහ ආරක්ෂාව',
      'full_name': 'සම්පූර්ණ නම',
      'delete_account': 'ගිණුම මකා දමන්න',
      'my_students': 'මගේ සිසුන්',
      'subscription': 'දායකත්වය',
      'coming_soon': 'ළඟදීම',
      'notifications': 'නිවේදන',
      'help_support': 'උදව් සහ සහාය',
      'edit': 'වෙනස් කරන්න',
      'parent_hub': 'දෙමාපිය අංශය',
      'hello_parent': 'ආයුබෝවන්',
      'children': 'දරුවන්',
      'this_week': 'මේ සතියේ',
      'connected': 'සම්බන්ධතා',
      'reports': 'වාර්තා',
      'messages': 'පණිවිඩ',
      'therapists': 'චිකිත්සකයින්',
      'your_children': 'ඔබේ දරුවන්',
      'select_a_child': 'දරුවෙකු තෝරන්න',
      'recent_activity': 'මෑත ක්‍රියාකාරකම්',
      'last_played': 'අවසන් වරට ක්‍රීඩා කළේ',
      'skills_mastered': 'කුසලතා ප්‍රගතිය',
      'no_students_yet': 'තවමත් සිසුන් නැත',
      'view_all_students': 'සිසුන් දෙනාම බලන්න →',
      'show_less': 'අඩුවෙන් පෙන්වන්න',
      'student_added': 'සිසුවා එකතු කරන ලදී!',
      'student_setup_ready_1': ' සියල්ල සකසා ඇති අතර ඉගෙනීමට සූදානම්.',
      'personalize_learning': 'පුද්ගලීකරණ ඉගෙනීම',
      'evaluation_desc_1': 'විනාඩි 2ක කෙටි ඇගයීමක් මගින් ',
      'evaluation_desc_2': 'ගේ සුවිශේෂී ඉගෙනුම් රටාව තේරුම් ගෙන ඔවුන්ට ගැලපෙන ක්‍රියාකාරකම් සකස් කිරීමට අපට උපකාරී වේ.',
      'personalized': 'පුද්ගලීකරණය කළ',
      '2_min': 'විනාඩි 2යි',
      'private': 'පෞද්ගලිකයි',
      'assessment_prompt_desc': 'විනාඩි 2ක කෙටි ඇගයීමක් මගින් ඔවුන්ගේ සුවිශේෂී ඉගෙනුම් රටාව තේරුම් ගෙන ඔවුන්ට ගැලපෙන ක්‍රියාකාරකම් සකස් කිරීමට අපට උපකාරී වේ.',
      'add_student': 'සිසුවෙකු එකතු කරන්න',
      'pending': 'නිම කරන්න',
      'completed': 'සම්පූර්ණයි',
      'premium_coming_soon': 'වාරික සැලසුම් ළඟදීම!',
      'premium_desc': 'ඔබේ දරුවාගේ ඉගෙනුම් ගමන සුපිරි කිරීමට අප විසින් විශිෂ්ට වාරික විශේෂාංග නිර්මාණය කරමින් සිටිමු.',
      'login_alerts': 'පිවිසුම් ඇඟවීම්',
      'login_alerts_desc': 'ඔබගේ ගිණුමට නව උපාංගයකින් පිවිසෙන විට දැනුම් දෙන්න.',
      'learning_progress': 'ඉගෙනුම් ප්‍රගතිය',
      'learning_progress_desc': 'ඔබේ දරුවා පරීක්ෂණයක් හෝ සන්ධිස්ථානයක් සම්පූර්ණ කළ විට දැනුම් දෙන්න.',
      'app_updates': 'යෙදුම් යාවත්කාලීන සහ විශේෂාංග',
      'app_updates_desc': 'නව අධ්‍යාපනික මෙවලම් පිළිබඳ වැදගත් නිවේදන ලබා ගන්න.',
      'email_support': 'විද්‍යුත් තැපැල් සහාය',
      'phone_support': 'දුරකථන සහාය',
      'faq': 'නිතර අසන ප්‍රශ්න',
      'logout': 'ඉවත් වන්න',
      'activities': 'ක්‍රියාකාරකම්',
      'accuracy': 'නිරවද්‍යතාව',
      'day_streak': 'අඛණ්ඩව ඉගෙනගත් දින',
      'stars_earned': 'ලබාගත් තරු',
      'weekly_activity': 'සතිපතා ක්‍රියාකාරකම්',
      'recent_skills': 'මෑත කුසලතා',
      'view_advanced_reports': 'උසස් වාර්තා සහ තාප සිතියම් බලන්න',
      'progress_report': 'ප්‍රගති වාර්තාව',
      'no_activities_played': 'තවමත් ක්‍රියාකාරකම් කර නැත',
      'whos_learning_today': 'අද ඉගෙන ගන්නේ කවුද?',
      'ready': 'සූදානම්',
      
      // Parent Hub Additions
      'last_active_prefix': 'අවසන් වරට ක්‍රියාකාරී වූයේ: ',
      'view_progress_btn': 'ප්‍රගතිය බලන්න →',
      'never': 'කිසිදාක නැත',
      'recent': 'මෑතකදී',
      'add_student_first_msg': 'ප්‍රගතිය බැලීමට පළමුව සිසුවෙකු ඇතුළත් කරන්න',
      'add_student_settings_hint': 'පළමු සිසුවා ඇතුළත් කිරීමට විකල්ප වෙත යන්න',
      
      'add_student_subtitle': 'ආරම්භ කිරීමට සිසුවෙකු එකතු කරන්න',
      'assessment_profile': 'ඇගයීම් ගිණුම',
      'select_area_evaluate': 'ඇගයීමට සුදුසු අංශයක් තෝරන්න',
      'cat_basic': 'මූලික ඩිස්ලෙක්සියා පරීක්ෂණය',
      'cat_reading': 'කියවීම හා දෘශ්‍ය සංජානන අපහසුතා',
      'cat_writing': 'ලිවීම සම්බන්ධ අපහසුතා',
      'cat_other': 'වෙනත් අපහසුතා',
      'btn_yes': 'ඔව්',
      'btn_no': 'නැත',
      'question_prefix': 'ප්‍රශ්නය ',
      'btn_finish_evaluation': 'ඇගයීම අවසන් කරන්න',

      // Add/Edit Student
      'add_student_desc': 'අමතර දරුවෙකු නොමිලේ එකතු කරන්න. ඔබගේ ගිණුමට දරුවන් 5 දෙනෙකු දක්වා එකතු කළ හැක.',
      'choose_avatar': 'ගිණුම සඳහා පින්තූරයක් තෝරන්න',
      'fantasy': 'ෆැන්ටසි',
      'kids': 'ළමයි',
      'student_first_name_hint': 'දරුවාගේ මුල් නම',
      'student_last_name_hint': 'දරුවාගේ අවසන් නම',
      'required_field': 'අවශ්‍යයි',
      'grade_1': '1 ශ්‍රේණිය',
      'auto_set': 'ස්වයංක්‍රීය',
      'daily_limit_prefix': 'දෛනික සීමාව: ',
      'student_updated_success': 'සිසුවා සාර්ථකව යාවත්කාලීන කෙරිණි!',
      'grade_set_info': 'ශ්‍රේණිය 1 ශ්‍රේණිය ලෙස සකසා ඇත',
      'save_changes': 'වෙනස්කම් සුරකින්න',
      'update_changes': 'යාවත්කාලීන කරන්න',
      'edit_student': 'සිසුවා සංස්කරණය කරන්න',
      'no_limit': 'සීමාවක් නොමැත',
      'minutes': 'මිනිත්තු',
      'hours': 'පැය',
      'hour': 'පැය',

      // Consent Screen
      'parental_consent': 'දෙමාපිය කැමැත්ත',
      'student_protection_agreement': 'සිසු ආරක්ෂණ ගිවිසුම',
      'consent_review_terms': 'ඉදිරියට යාමට පෙර කරුණාකර පහත නියමයන් කියවා එකඟ වන්න.',
      'consent_items': 'කැමැත්ත ලබාදිය යුතු කරුණු',
      'guardian_confirmation_title': 'භාරකරු තහවුරු කිරීම',
      'guardian_confirmation_desc': 'මා මෙම දරුවාගේ දෙමාපියන් හෝ නීත්‍යානුකූල භාරකරු බවත්, ඔවුන් වෙනුවෙන් කැමැත්ත ලබා දීමට මට බලය ඇති බවත් මම තහවුරු කරමි.',
      'data_collection_title': 'ඉගෙනුම් දත්ත එකතු කිරීම',
      'data_collection_desc': 'මාගේ දරුවාගේ අධ්‍යාපනික අත්දැකීම් ඔවුන්ට ගැලපෙන අයුරින් සැකසීමට ඔවුන්ගේ ඉගෙනුම් දත්ත (ප්‍රතිචාර, ප්‍රගතිය සහ කාර්යසාධනය) එකතු කිරීම සහ සැකසීම සඳහා මම කැමැත්ත ප්‍රකාශ කරමි.',
      'screening_purpose_title': 'ඩිස්ලෙක්සියා පරීක්ෂාවේ අරමුණ',
      'screening_purpose_desc': 'මෙම යෙදුම 1 ශ්‍රේණියේ ඩිස්ලෙක්සියා පරීක්ෂාව සහ ඉගෙනුම් සහාය සඳහා නිර්මාණය කර ඇති බව මම තේරුම් ගනිමි. එය වෛද්‍ය රෝග විනිශ්චය ලබා නොදෙන අතර වෘත්තීය මාර්ගෝපදේශනය සමඟ භාවිතා කළ යුතුය.',
      'terms_privacy_title': 'භාවිත නියමයන් සහ රහස්‍යතා ප්‍රතිපත්තිය',
      'terms_privacy_desc': 'මා භාවිත නියමයන් සහ රහස්‍යතා ප්‍රතිපත්තිය කියවා ඊට එකඟ වී ඇත. මාගේ දරුවාගේ දත්ත ආරක්ෂිතව ගබඩා කරනු ඇති අතර තෙවන පාර්ශවයන් සමඟ බෙදා නොගන්නා බව මම තේරුම් ගනිමි.',
      'digital_signature': 'ඩිජිටල් අත්සන',
      'digital_signature_desc': 'ඔබගේ ඩිජිටල් අත්සන ලෙස ඔබගේ සම්පූර්ණ නම පහතින් ටයිප් කරන්න.',
      'signature_hint': 'දෙමාපියන්ගේ / භාරකරුගේ සම්පූර්ණ නම',
      'date_prefix': 'දිනය: ',
      'agree_continue': 'මම එකඟ වී ඉදිරියට යමි',
      'withdraw_consent_info': 'ඔබට ඕනෑම වේලාවක දෙමාපිය ගිණුම් සැකසීම් හරහා\nඔබගේ කැමැත්ත ඉවත් කරගත හැක.',
    },
    'en': {
      'welcome_title': 'Welcome!',
      'welcome_subtitle': 'your sinhala learning\nadventure awaits!',
      'welcome_btn_signup': 'get started',
      'welcome_btn_signin': 'i already have an account',
      'btn_signin': 'sign in',
      'signing_in': 'signing in...',
      'btn_signup': 'sign up',
      'email': 'email',
      'email_hint': 'your email address',
      'password': 'password',
      'password_hint': 'your password',
      'password_hint_create': 'create password',
      'forgot_password': 'forgot password?',
      'forgot_password_desc': 'Don\'t worry! It happens. Please enter the email address associated with your account.',
      'sending_code': 'sending code...',
      'send_code': 'send code',
      'check_email': 'Check your email',
      'otp_sent_to': 'We\'ve sent a code to\n',
      'otp_enter_below': '\n\nPlease enter the code below to verify.',
      'resend_code_in': 'Resend code in {time}',
      'resend_otp_now': 'Resend code now',
      'verify_code': 'Verify Code',
      'dont_have_account': 'don\'t have an account? ',
      'already_have_account': 'already have an account? ',
      'signin_title': 'welcome back!',
      'signin_subtitle': 'sign in to continue your adventure',
      'signup_title': 'create your account',
      'signup_subtitle': 'join the learning adventure today',
      'parent_name': 'Parent\'s Name',
      'parent_name_hint': 'your name',
      'role_parent': 'parent',
      'role_therapist': 'therapist',
      'specialization_hint': 'specialization (e.g. speech therapist)',
      'clinic_hint': 'clinic name (optional)',
      'or': 'or',
      'mobile_number': 'mobile number',
      'mobile_number_hint': 'Your mobile number',
      'confirm_password': 'Confirm Password',
      'confirm_password_hint': 'Re-enter your password',
      'agree_terms': 'I agree to Sipsara\'s Terms of Use and Privacy Policy.',
      'benefit_private': 'private',
      'start_assessment': 'start assessment',
      'maybe_later': 'maybe later',
      'assessment_later_desc': 'you can always start this from the student\'s profile.',
      'start_from_profile': 'you can always start this from the student\'s profile.',
      'language': 'Language',
      'select_language': 'Select Language',
      'settings': 'Settings',
      'field_required': 'This field is required',
      'invalid_email': 'Please enter a valid email address',
      'invalid_phone': 'Please enter a valid phone number',
      'password_short': 'Password must be at least 6 characters long',
      'passwords_dont_match': 'Passwords do not match',
      'must_agree_terms': 'You must agree to the Terms of Use and Privacy Policy',
      'or_continue_with': 'Or continue with',
      'error_occurred': 'An error occurred. Please try again.',
      'change': 'change',
      'parent_account': 'parent account',
      'account_security': 'account & security',
      'full_name': 'full name',
      'delete_account': 'delete account',
      'my_students': 'my students',
      'subscription': 'subscription',
      'coming_soon': 'coming soon',
      'notifications': 'notifications',
      'help_support': 'help & support',
      'edit': 'edit',
      'parent_hub': 'parent hub',
      'hello_parent': 'hello',
      'children': 'children',
      'this_week': 'this week',
      'connected': 'connected',
      'reports': 'reports',
      'messages': 'messages',
      'therapists': 'therapists',
      'your_children': 'your children',
      'select_a_child': 'Select a Child',
      'recent_activity': 'recent activity',
      'last_played': 'last played',
      'skills_mastered': 'skills mastered',
      'student_added': 'student added!',
      'student_setup_ready_1': ' is all set up and ready to learn.',
      'personalize_learning': 'personalize learning',
      'evaluation_desc_1': 'a quick 2-minute evaluation will help us understand ',
      'evaluation_desc_2': '\'s unique learning style and tailor activities specifically for them.',
      'personalized': 'personalized',
      '2_min': '2 mins',
      'private': 'private',
      'assessment_prompt_desc': 'a quick 2-minute assessment helps us understand their unique learning style and tailor activities specifically for them.',
      'add_student': 'add student',
      'pending': 'Pending',
      'completed': 'Completed',
      'premium_coming_soon': 'premium plans coming soon!',
      'premium_desc': "we're crafting amazing premium features to supercharge your child's learning journey.",
      'login_alerts': 'login alerts',
      'login_alerts_desc': 'get notified when your account is accessed from a new device.',
      'learning_progress': 'learning progress',
      'learning_progress_desc': 'get notified when your child completes a screening or milestone.',
      'app_updates': 'app updates & features',
      'app_updates_desc': 'receive important announcements about new educational tools.',
      'email_support': 'email support',
      'phone_support': 'phone support',
      'faq': 'FAQ',
      'logout': 'logout',
      'activities': 'activities',
      'accuracy': 'accuracy',
      'day_streak': 'day streak',
      'stars_earned': 'stars earned',
      'weekly_activity': 'weekly activity',
      'recent_skills': 'recent skills',
      'view_advanced_reports': 'View Advanced Reports & Heatmap',
      'progress_report': 'progress report',
      'no_activities_played': 'No activities played yet',
      'whos_learning_today': 'who\'s learning today?',
      'ready': 'Ready',

      // Parent Hub Additions
      'last_active_prefix': 'last active: ',
      'view_progress_btn': 'view progress →',
      'never': 'never',
      'recent': 'recent',
      'add_student_first_msg': 'add a student first to view progress',
      'add_student_settings_hint': 'go to settings to add your first student',

      'add_student_subtitle': 'add a student to get started',
      'assessment_profile': 'Assessment Profile',
      'select_area_evaluate': 'Select an area to evaluate.',
      'cat_basic': 'Basic Dyslexia Evaluation',
      'cat_reading': 'Reading & Visual Perception',
      'cat_writing': 'Writing Difficulties',
      'cat_other': 'Other Associated Difficulties',
      'btn_yes': 'Yes',
      'btn_no': 'No',
      'question_prefix': 'Question ',
      'btn_next_question': 'Next Question',
      'btn_finish_evaluation': 'Finish Evaluation',

      // Add/Edit Student
      'add_student_desc': 'add an additional student for free. you are allowed to add up to 5 children to your account.',
      'choose_avatar': 'choose a character profile picture',
      'fantasy': 'Fantasy',
      'kids': 'Kids',
      'student_first_name_hint': 'student first name',
      'student_last_name_hint': 'student last name',
      'required_field': 'required',
      'grade_1': 'Grade 1',
      'auto_set': 'auto-set',
      'daily_limit_prefix': 'daily limit: ',
      'student_updated_success': 'student updated successfully!',
      'grade_set_info': 'grade is set to Grade 1',
      'save_changes': 'save changes',
      'update_changes': 'update changes',
      'edit_student': 'edit student',
      'no_limit': 'No Limit',
      'minutes': 'minutes',
      'hours': 'hours',
      'hour': 'hour',

      // Consent Screen
      'parental_consent': 'parental consent',
      'student_protection_agreement': 'student protection agreement',
      'consent_review_terms': 'please review and accept the following terms before proceeding.',
      'consent_items': 'consent items',
      'guardian_confirmation_title': 'guardian confirmation',
      'guardian_confirmation_desc': 'I confirm that I am the parent or legal guardian of this child and have the authority to provide consent on their behalf.',
      'data_collection_title': 'learning data collection',
      'data_collection_desc': 'I consent to the collection and processing of my child\'s learning data (responses, progress, and performance) to personalize their educational experience.',
      'screening_purpose_title': 'dyslexia screening purpose',
      'screening_purpose_desc': 'I understand that this app is designed for Grade 1 dyslexia screening and learning support. It does not provide medical diagnoses and should be used alongside professional guidance.',
      'terms_privacy_title': 'terms of use & privacy policy',
      'terms_privacy_desc': 'I have read and agree to the terms of use and privacy policy. I understand my child\'s data will be stored securely and will not be shared with third parties.',
      'digital_signature': 'digital signature',
      'digital_signature_desc': 'type your full name below as your digital signature.',
      'signature_hint': 'parent / guardian full name',
      'date_prefix': 'date: ',
      'agree_continue': 'i agree & continue',
      'withdraw_consent_info': 'you can withdraw consent at any time\nfrom the parent account settings.',
    }
  };
}
